CREATE TABLE `drivers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`age` int NOT NULL,
	`gender` enum('male','female') NOT NULL,
	`licenseNumber` varchar(100) NOT NULL,
	`licenseState` varchar(2) NOT NULL,
	`vehicleType` varchar(100) NOT NULL,
	`vehicleMake` varchar(100),
	`vehicleModel` varchar(100),
	`vehicleYear` int,
	`licensePlate` varchar(20),
	`insuranceProvider` varchar(255),
	`insurancePolicyNumber` varchar(100),
	`status` enum('active','inactive','suspended','pending_approval') NOT NULL DEFAULT 'pending_approval',
	`verified` enum('yes','no') NOT NULL DEFAULT 'no',
	`rating` varchar(5),
	`totalDeliveries` int NOT NULL DEFAULT 0,
	`currentLatitude` varchar(20),
	`currentLongitude` varchar(20),
	`lastLocationUpdate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `drivers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `gpsTracking` (
	`id` int AUTO_INCREMENT NOT NULL,
	`shipmentId` int NOT NULL,
	`driverId` int NOT NULL,
	`latitude` varchar(20) NOT NULL,
	`longitude` varchar(20) NOT NULL,
	`speed` varchar(10),
	`heading` varchar(10),
	`accuracy` varchar(10),
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `gpsTracking_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shipments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`driverId` int NOT NULL,
	`farmerId` int NOT NULL,
	`farmerBusinessName` varchar(255) NOT NULL,
	`consumerId` int NOT NULL,
	`trackingNumber` varchar(100) NOT NULL,
	`status` enum('pending','assigned','picked_up','in_transit','delivered','cancelled') NOT NULL DEFAULT 'pending',
	`pickupAddress` text NOT NULL,
	`pickupCity` varchar(100) NOT NULL,
	`pickupState` varchar(2) NOT NULL,
	`pickupZip` varchar(10) NOT NULL,
	`pickupLatitude` varchar(20) NOT NULL,
	`pickupLongitude` varchar(20) NOT NULL,
	`deliveryAddress` text NOT NULL,
	`deliveryCity` varchar(100) NOT NULL,
	`deliveryState` varchar(2) NOT NULL,
	`deliveryZip` varchar(10) NOT NULL,
	`deliveryLatitude` varchar(20) NOT NULL,
	`deliveryLongitude` varchar(20) NOT NULL,
	`distanceMiles` varchar(10),
	`estimatedDeliveryTime` timestamp,
	`actualPickupTime` timestamp,
	`actualDeliveryTime` timestamp,
	`transportationFee` int NOT NULL,
	`platformCommission` int NOT NULL,
	`driverPayout` int NOT NULL,
	`packageWeight` varchar(20),
	`packageValue` int NOT NULL,
	`specialInstructions` text,
	`signatureRequired` enum('yes','no') NOT NULL DEFAULT 'yes',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shipments_id` PRIMARY KEY(`id`),
	CONSTRAINT `shipments_trackingNumber_unique` UNIQUE(`trackingNumber`)
);
--> statement-breakpoint
CREATE TABLE `transportationCompanies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`companyName` varchar(255) NOT NULL,
	`businessLicenseNumber` varchar(100) NOT NULL,
	`dotNumber` varchar(100),
	`mcNumber` varchar(100),
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`address` text NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(2) NOT NULL,
	`zipCode` varchar(10) NOT NULL,
	`insuranceProvider` varchar(255) NOT NULL,
	`insurancePolicyNumber` varchar(100) NOT NULL,
	`insuranceCoverage` int NOT NULL,
	`status` enum('active','inactive','suspended','pending_approval') NOT NULL DEFAULT 'pending_approval',
	`verified` enum('yes','no') NOT NULL DEFAULT 'no',
	`totalDrivers` int NOT NULL DEFAULT 0,
	`totalDeliveries` int NOT NULL DEFAULT 0,
	`rating` varchar(5),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `transportationCompanies_id` PRIMARY KEY(`id`)
);
