CREATE TABLE `supplierApplications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`brandName` varchar(255) NOT NULL,
	`contactName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(30),
	`website` varchar(500),
	`businessType` varchar(100) NOT NULL,
	`description` text,
	`licenseNumber` varchar(100),
	`state` varchar(2) NOT NULL,
	`city` varchar(100),
	`shipsNationwide` boolean NOT NULL DEFAULT false,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`reviewedAt` timestamp,
	`reviewedBy` int,
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `supplierApplications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `supplierProducts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`supplierId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`strainName` varchar(255),
	`category` enum('seeds','clones','equipment','nutrients','packaging','lab_services','consulting','lighting','irrigation','other') NOT NULL,
	`subcategory` varchar(100),
	`description` text,
	`photoUrl` varchar(1000),
	`unitPriceCents` int NOT NULL,
	`unit` varchar(50) NOT NULL DEFAULT 'each',
	`minOrderQty` int NOT NULL DEFAULT 1,
	`inStock` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `supplierProducts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `suppliers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`slug` varchar(120) NOT NULL,
	`brandName` varchar(255) NOT NULL,
	`description` text,
	`logoUrl` varchar(1000),
	`websiteUrl` varchar(500),
	`instagramUrl` varchar(500),
	`facebookUrl` varchar(500),
	`twitterUrl` varchar(500),
	`city` varchar(100),
	`state` varchar(2),
	`shipsNationwide` boolean NOT NULL DEFAULT false,
	`status` enum('pending','approved','rejected','suspended') NOT NULL DEFAULT 'pending',
	`featured` boolean NOT NULL DEFAULT false,
	`reviewedAt` timestamp,
	`reviewedBy` int,
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `suppliers_id` PRIMARY KEY(`id`),
	CONSTRAINT `suppliers_slug_unique` UNIQUE(`slug`)
);
