CREATE TABLE `supplierApplications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`businessName` varchar(255) NOT NULL,
	`supplierType` enum('equipment','seeds','nutrients','lighting','soil','packaging','services','technology','other') NOT NULL,
	`contactName` varchar(255) NOT NULL,
	`contactEmail` varchar(320) NOT NULL,
	`contactPhone` varchar(30),
	`websiteUrl` text,
	`state` varchar(2) NOT NULL,
	`city` varchar(100),
	`description` text,
	`nationwide` enum('yes','no') NOT NULL DEFAULT 'yes',
	`message` text,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `supplierApplications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `supplierProducts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`supplierId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`category` enum('equipment','seeds','nutrients','lighting','soil','packaging','services','technology','other') NOT NULL,
	`subcategory` varchar(100),
	`unitPrice` int NOT NULL,
	`unitLabel` varchar(50) NOT NULL DEFAULT 'unit',
	`minOrderQty` int NOT NULL DEFAULT 1,
	`inStock` enum('yes','no') NOT NULL DEFAULT 'yes',
	`localPickup` enum('yes','no') NOT NULL DEFAULT 'no',
	`photos` text,
	`externalUrl` text,
	`status` enum('active','inactive','sold_out') NOT NULL DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `supplierProducts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `suppliers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`businessName` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`supplierType` enum('equipment','seeds','nutrients','lighting','soil','packaging','services','technology','other') NOT NULL,
	`description` text,
	`logoUrl` text,
	`websiteUrl` text,
	`instagramUrl` text,
	`facebookUrl` text,
	`twitterUrl` text,
	`linkedinUrl` text,
	`youtubeUrl` text,
	`contactName` varchar(255),
	`contactEmail` varchar(320),
	`contactPhone` varchar(30),
	`state` varchar(2),
	`city` varchar(100),
	`zipCode` varchar(10),
	`nationwide` enum('yes','no') NOT NULL DEFAULT 'yes',
	`status` enum('pending','approved','suspended') NOT NULL DEFAULT 'pending',
	`featured` enum('yes','no') NOT NULL DEFAULT 'no',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `suppliers_id` PRIMARY KEY(`id`),
	CONSTRAINT `suppliers_slug_unique` UNIQUE(`slug`)
);
