/**
 * ZAPPAY Hemp/CBD Product Seed Script
 * Seeds 55 production-ready hemp/CBD product listings.
 * Hemp products are legal in all 50 states under the 2018 Farm Bill (<0.3% THC).
 * Run with: node scripts/seed-hemp.mjs
 */

import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(__dirname, '..', '.env') });

// All hemp products use farmerId=1 (the platform owner / admin)
// They are marked isHemp='yes' and category='hemp', available in all 50 states
const FARMER_ID = 1;

const hempProducts = [
  // ── HEMP FLOWER ──────────────────────────────────────────────────────────────
  {
    name: "Sour Space Candy Hemp Flower",
    strain: "Sour Space Candy",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.2",
    cbdPercentage: "18.5",
    price: 1299, // $12.99/gram
    retailPrice: 1799,
    quantity: 500,
    unit: "gram",
    description: "Sour Space Candy is one of the most popular hemp flower strains on the market. This award-winning cultivar delivers a complex terpene profile with notes of sour apple, tropical fruit, and earthy undertones. Lab-tested at 18.5% CBD with <0.2% THC — federally legal in all 50 states.",
    effects: "Relaxing, Stress Relief, Mood Boost",
    flavor: "Sour Apple, Tropical, Earthy",
    bestFor: "Daytime use, Anxiety relief, Social situations",
    rating: "4.9",
    isFeatured: "yes",
  },
  {
    name: "Cherry Wine Hemp Flower",
    strain: "Cherry Wine",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.15",
    cbdPercentage: "16.2",
    price: 1199,
    retailPrice: 1699,
    quantity: 400,
    unit: "gram",
    description: "Cherry Wine is a beloved hemp cultivar known for its rich cherry and black pepper aroma. Bred from The Wife and Charlotte's Cherries, this strain produces dense, resinous buds with a smooth smoke and calming effects. Perfect for evening relaxation.",
    effects: "Calming, Pain Relief, Sleep Aid",
    flavor: "Cherry, Black Pepper, Floral",
    bestFor: "Evening use, Pain management, Sleep",
    rating: "4.8",
    isFeatured: "yes",
  },
  {
    name: "Elektra Hemp Flower",
    strain: "Elektra",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.18",
    cbdPercentage: "15.8",
    price: 1099,
    retailPrice: 1599,
    quantity: 350,
    unit: "gram",
    description: "Elektra is a cross of ACDC and Erba Crossing, producing a citrus-forward hemp flower with notes of orange, mango, and pine. This high-CBD strain is known for its uplifting effects and is a favorite among those seeking daytime relief without impairment.",
    effects: "Uplifting, Focus, Stress Relief",
    flavor: "Orange, Mango, Pine",
    bestFor: "Daytime use, Focus, Creative work",
    rating: "4.7",
  },
  {
    name: "Hawaiian Haze Hemp Flower",
    strain: "Hawaiian Haze",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.12",
    cbdPercentage: "17.3",
    price: 1199,
    retailPrice: 1699,
    quantity: 300,
    unit: "gram",
    description: "Hawaiian Haze brings the spirit of the islands to your hemp experience. This tropical cultivar features bright notes of pineapple, mango, and citrus with a light, airy smoke. High CBD content makes it ideal for daytime use and mood elevation.",
    effects: "Euphoric, Energizing, Mood Boost",
    flavor: "Pineapple, Mango, Citrus",
    bestFor: "Morning use, Social events, Creative projects",
    rating: "4.8",
  },
  {
    name: "Special Sauce Hemp Flower",
    strain: "Special Sauce",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.19",
    cbdPercentage: "20.1",
    price: 1399,
    retailPrice: 1999,
    quantity: 250,
    unit: "gram",
    description: "Special Sauce is a premium hemp strain with one of the highest CBD concentrations available. This indica-dominant cultivar produces thick, frosty buds with a complex aroma of berries, earth, and sweet candy. Exceptional for relaxation and full-body relief.",
    effects: "Deep Relaxation, Pain Relief, Anti-inflammatory",
    flavor: "Berry, Sweet Candy, Earth",
    bestFor: "Evening use, Chronic pain, Muscle recovery",
    rating: "4.9",
    isFeatured: "yes",
  },
  {
    name: "Suver Haze Hemp Flower",
    strain: "Suver Haze",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.17",
    cbdPercentage: "19.4",
    price: 1299,
    retailPrice: 1799,
    quantity: 320,
    unit: "gram",
    description: "Suver Haze is a sativa-dominant hemp strain known for its exceptional terpene profile and high CBD content. A cross of Suver #8 and ERB, it delivers notes of pepper, myrcene, and citrus with energizing, clear-headed effects.",
    effects: "Energizing, Clear-headed, Anti-anxiety",
    flavor: "Pepper, Citrus, Herbal",
    bestFor: "Daytime use, Productivity, Anxiety relief",
    rating: "4.7",
  },
  {
    name: "Lifter Hemp Flower",
    strain: "Lifter",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.14",
    cbdPercentage: "16.9",
    price: 1099,
    retailPrice: 1499,
    quantity: 400,
    unit: "gram",
    description: "Lifter lives up to its name — this uplifting hemp strain is perfect for those seeking a mood boost without any psychoactive effects. With notes of cheese, fuel, and tropical fruit, Lifter provides a unique sensory experience alongside its therapeutic benefits.",
    effects: "Mood Lift, Energy, Focus",
    flavor: "Cheese, Fuel, Tropical",
    bestFor: "Morning use, Depression relief, Motivation",
    rating: "4.6",
  },
  {
    name: "Bubba Kush CBD Hemp Flower",
    strain: "Bubba Kush CBD",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.16",
    cbdPercentage: "14.5",
    price: 1099,
    retailPrice: 1599,
    quantity: 280,
    unit: "gram",
    description: "The classic Bubba Kush genetics reimagined as a high-CBD hemp cultivar. This indica-dominant strain delivers the same earthy, coffee, and chocolate notes of the original with deeply relaxing effects and zero psychoactivity. Perfect for nighttime use.",
    effects: "Sedating, Full-body Relaxation, Sleep",
    flavor: "Coffee, Chocolate, Earth",
    bestFor: "Insomnia, Nighttime use, Stress",
    rating: "4.7",
  },
  {
    name: "OG Kush CBD Hemp Flower",
    strain: "OG Kush CBD",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.19",
    cbdPercentage: "15.2",
    price: 1199,
    retailPrice: 1699,
    quantity: 300,
    unit: "gram",
    description: "OG Kush CBD brings the legendary West Coast genetics into the hemp world. This balanced hybrid delivers the iconic earthy, pine, and lemon terpene profile with calming, stress-relieving effects. A must-have for OG fans seeking CBD benefits.",
    effects: "Stress Relief, Relaxation, Euphoria",
    flavor: "Lemon, Pine, Earth",
    bestFor: "Stress relief, After work, Social use",
    rating: "4.8",
  },
  {
    name: "Blueberry Kush CBD Hemp Flower",
    strain: "Blueberry Kush CBD",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.13",
    cbdPercentage: "17.8",
    price: 1299,
    retailPrice: 1799,
    quantity: 220,
    unit: "gram",
    description: "Blueberry Kush CBD is an indica-dominant hemp strain with a sweet blueberry aroma and deeply relaxing effects. Rich in CBD and minor cannabinoids, this strain is ideal for those seeking relief from anxiety, pain, and insomnia.",
    effects: "Relaxing, Pain Relief, Sleep",
    flavor: "Blueberry, Sweet, Vanilla",
    bestFor: "Nighttime use, Pain, Anxiety",
    rating: "4.8",
  },

  // ── CBD PRE-ROLLS ─────────────────────────────────────────────────────────────
  {
    name: "Sour Space Candy CBD Pre-Roll",
    strain: "Sour Space Candy",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.2",
    cbdPercentage: "18.5",
    price: 699,
    retailPrice: 999,
    quantity: 200,
    unit: "pre-roll",
    description: "Pre-rolled and ready to enjoy — our Sour Space Candy CBD pre-rolls are crafted from premium hemp flower with no additives. Each 1g pre-roll is hand-rolled in unbleached rice paper for a clean, smooth experience.",
    effects: "Relaxing, Stress Relief, Mood Boost",
    flavor: "Sour Apple, Tropical, Earthy",
    bestFor: "On-the-go, Quick relief, Convenience",
    rating: "4.8",
    isFeatured: "yes",
  },
  {
    name: "Cherry Wine CBD Pre-Roll",
    strain: "Cherry Wine",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.15",
    cbdPercentage: "16.2",
    price: 649,
    retailPrice: 899,
    quantity: 180,
    unit: "pre-roll",
    description: "Cherry Wine CBD pre-rolls deliver the full flavor and therapeutic benefits of this beloved strain in a convenient, ready-to-smoke format. Each pre-roll contains 1g of premium hemp flower with no fillers.",
    effects: "Calming, Pain Relief, Sleep Aid",
    flavor: "Cherry, Black Pepper, Floral",
    bestFor: "Evening use, Pain management, Convenience",
    rating: "4.7",
  },
  {
    name: "Hawaiian Haze CBD Pre-Roll 5-Pack",
    strain: "Hawaiian Haze",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.12",
    cbdPercentage: "17.3",
    price: 2999,
    retailPrice: 3999,
    quantity: 100,
    unit: "5-pack",
    description: "Our Hawaiian Haze 5-pack is perfect for those who want to stock up on their favorite tropical CBD strain. Each pack contains five 1g pre-rolls made from premium hemp flower. Great value for daily users.",
    effects: "Euphoric, Energizing, Mood Boost",
    flavor: "Pineapple, Mango, Citrus",
    bestFor: "Daily use, Value packs, Sharing",
    rating: "4.8",
  },
  {
    name: "Mixed CBD Pre-Roll Sampler Pack",
    strain: "Mixed Strains",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.18",
    cbdPercentage: "16.0",
    price: 3499,
    retailPrice: 4999,
    quantity: 80,
    unit: "10-pack",
    description: "Can't decide on a strain? Our Mixed CBD Pre-Roll Sampler includes 10 pre-rolls across our top hemp strains: Sour Space Candy, Cherry Wine, Elektra, Hawaiian Haze, and Special Sauce. Two of each strain — perfect for exploring.",
    effects: "Varied, Relaxing, Uplifting",
    flavor: "Mixed — Fruity, Earthy, Floral",
    bestFor: "New users, Exploration, Gifting",
    rating: "4.9",
    isFeatured: "yes",
  },

  // ── CBD OILS & TINCTURES ──────────────────────────────────────────────────────
  {
    name: "Full Spectrum CBD Oil 1000mg",
    strain: "Full Spectrum Hemp Extract",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "3.3",
    price: 4999,
    retailPrice: 7999,
    quantity: 150,
    unit: "30ml bottle",
    description: "Our 1000mg Full Spectrum CBD Oil contains the complete cannabinoid profile of the hemp plant, including CBD, CBG, CBN, and trace amounts of THC (<0.3%). Extracted using CO2 supercritical extraction for maximum purity. Available in natural hemp flavor.",
    effects: "Full-body Relief, Anti-inflammatory, Sleep Support",
    flavor: "Natural Hemp",
    bestFor: "Daily wellness, Chronic conditions, Sleep",
    rating: "4.8",
    isFeatured: "yes",
  },
  {
    name: "Full Spectrum CBD Oil 2500mg",
    strain: "Full Spectrum Hemp Extract",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "8.3",
    price: 9999,
    retailPrice: 14999,
    quantity: 100,
    unit: "30ml bottle",
    description: "Our high-potency 2500mg Full Spectrum CBD Oil is designed for those requiring stronger doses. Each 1ml serving delivers approximately 83mg of CBD alongside the full spectrum of hemp cannabinoids and terpenes.",
    effects: "Potent Relief, Anti-inflammatory, Anxiety",
    flavor: "Natural Hemp",
    bestFor: "High-tolerance users, Severe conditions, Chronic pain",
    rating: "4.9",
  },
  {
    name: "Broad Spectrum CBD Oil 1500mg (THC-Free)",
    strain: "Broad Spectrum Hemp Extract",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "5.0",
    price: 6999,
    retailPrice: 9999,
    quantity: 120,
    unit: "30ml bottle",
    description: "Our Broad Spectrum CBD Oil is completely THC-free, making it ideal for those subject to drug testing or who prefer to avoid THC entirely. Contains CBD, CBG, CBN, and other beneficial cannabinoids with zero THC.",
    effects: "Relaxation, Anti-anxiety, Focus",
    flavor: "Natural Hemp, Mint available",
    bestFor: "Drug-tested individuals, THC-sensitive users, Daily wellness",
    rating: "4.8",
  },
  {
    name: "CBD Isolate Oil 1000mg (Pure CBD)",
    strain: "CBD Isolate",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "3.3",
    price: 3999,
    retailPrice: 5999,
    quantity: 200,
    unit: "30ml bottle",
    description: "Pure CBD isolate oil with zero other cannabinoids. 99.9% pure CBD suspended in MCT oil. Completely odorless and tasteless — ideal for adding to food, beverages, or taking sublingually. Perfect for those who want precise CBD dosing.",
    effects: "Precise Dosing, Anti-anxiety, Focus",
    flavor: "Flavorless",
    bestFor: "Precise dosing, Cooking, Sensitive users",
    rating: "4.7",
  },
  {
    name: "CBG + CBD Oil 1000mg",
    strain: "CBG + CBD Blend",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "2.5",
    price: 5999,
    retailPrice: 8999,
    quantity: 100,
    unit: "30ml bottle",
    description: "Our CBG + CBD Oil combines two powerful cannabinoids for enhanced therapeutic benefits. CBG (cannabigerol) is known as the 'mother cannabinoid' and works synergistically with CBD to provide superior anti-inflammatory and neuroprotective effects.",
    effects: "Anti-inflammatory, Neuroprotective, Focus",
    flavor: "Natural Hemp",
    bestFor: "Inflammation, Neurological conditions, Focus",
    rating: "4.8",
  },
  {
    name: "CBD Sleep Tincture 750mg + Melatonin",
    strain: "Full Spectrum Hemp + Melatonin",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.2",
    cbdPercentage: "2.5",
    price: 4499,
    retailPrice: 6499,
    quantity: 130,
    unit: "30ml bottle",
    description: "Our CBD Sleep Tincture combines 750mg of full spectrum CBD with 3mg of melatonin per serving for the ultimate sleep support formula. Lavender and chamomile terpenes enhance the calming effect. Take 30 minutes before bed.",
    effects: "Sleep Induction, Relaxation, Stress Relief",
    flavor: "Lavender, Chamomile",
    bestFor: "Insomnia, Sleep disorders, Nighttime routine",
    rating: "4.9",
    isFeatured: "yes",
  },

  // ── CBD EDIBLES ───────────────────────────────────────────────────────────────
  {
    name: "CBD Gummies 25mg Each (30-count)",
    strain: "Broad Spectrum Hemp Extract",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "2.5",
    price: 3999,
    retailPrice: 5999,
    quantity: 200,
    unit: "30-count jar",
    description: "Our CBD Gummies deliver 25mg of broad spectrum CBD per gummy in a delicious mixed berry flavor. Made with natural fruit flavors and colors, these vegan gummies are a convenient and tasty way to get your daily CBD dose.",
    effects: "Relaxation, Stress Relief, Mood Balance",
    flavor: "Mixed Berry, Watermelon, Citrus",
    bestFor: "Daily wellness, Stress, Convenience",
    rating: "4.8",
    isFeatured: "yes",
  },
  {
    name: "CBD Gummies 50mg Each (20-count)",
    strain: "Full Spectrum Hemp Extract",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "5.0",
    price: 4999,
    retailPrice: 7499,
    quantity: 150,
    unit: "20-count jar",
    description: "High-potency CBD gummies with 50mg of full spectrum CBD per piece. Ideal for those with higher CBD requirements or who have built up a tolerance. Each gummy contains the full spectrum of hemp cannabinoids for maximum entourage effect.",
    effects: "Potent Relaxation, Pain Relief, Sleep",
    flavor: "Tropical Mango, Strawberry",
    bestFor: "High-tolerance users, Chronic pain, Sleep",
    rating: "4.7",
  },
  {
    name: "CBD Sleep Gummies 25mg CBD + 5mg CBN",
    strain: "CBD + CBN Blend",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "2.5",
    price: 4499,
    retailPrice: 6499,
    quantity: 120,
    unit: "20-count jar",
    description: "Our CBD Sleep Gummies combine 25mg CBD with 5mg CBN (cannabinol) — the cannabinoid known for its sedative properties. Enhanced with L-theanine and passionflower extract for a comprehensive sleep support formula.",
    effects: "Sleep Induction, Sedating, Relaxation",
    flavor: "Blueberry Lavender",
    bestFor: "Insomnia, Sleep quality, Nighttime",
    rating: "4.9",
  },
  {
    name: "CBD Energy Gummies 15mg + B12",
    strain: "Broad Spectrum Hemp Extract",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "1.5",
    price: 3499,
    retailPrice: 4999,
    quantity: 180,
    unit: "30-count jar",
    description: "Start your day right with our CBD Energy Gummies. Each gummy contains 15mg of broad spectrum CBD combined with 500mcg of Vitamin B12 and natural caffeine from green tea extract for a clean, sustained energy boost.",
    effects: "Energy, Focus, Mood Boost",
    flavor: "Citrus Burst, Lemon",
    bestFor: "Morning use, Pre-workout, Productivity",
    rating: "4.6",
  },
  {
    name: "CBD Dark Chocolate Bar 200mg",
    strain: "CBD Isolate",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "2.0",
    price: 1999,
    retailPrice: 2999,
    quantity: 200,
    unit: "bar",
    description: "Indulge in our premium 72% dark chocolate infused with 200mg of CBD isolate. Each bar is divided into 10 squares of 20mg CBD each. Made with ethically sourced cacao and no artificial ingredients.",
    effects: "Relaxation, Mood Boost, Stress Relief",
    flavor: "Dark Chocolate, Sea Salt",
    bestFor: "Dessert, Gifting, Discreet use",
    rating: "4.8",
  },
  {
    name: "CBD Honey Sticks 10mg Each (20-pack)",
    strain: "Full Spectrum Hemp Extract",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "1.0",
    price: 2499,
    retailPrice: 3499,
    quantity: 150,
    unit: "20-pack",
    description: "Our CBD Honey Sticks are perfect for adding CBD to tea, coffee, or enjoying straight. Each stick contains 10mg of full spectrum CBD in raw, unfiltered honey. No artificial flavors or preservatives.",
    effects: "Gentle Relaxation, Wellness, Immune Support",
    flavor: "Raw Honey, Wildflower",
    bestFor: "Tea/coffee addition, Gentle dosing, Daily wellness",
    rating: "4.7",
  },

  // ── CBD TOPICALS ──────────────────────────────────────────────────────────────
  {
    name: "CBD Pain Relief Cream 1000mg",
    strain: "Full Spectrum Hemp Extract",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "3.3",
    price: 5999,
    retailPrice: 8999,
    quantity: 100,
    unit: "4oz jar",
    description: "Our CBD Pain Relief Cream delivers 1000mg of full spectrum CBD directly to the source of pain. Formulated with menthol, arnica, and camphor for immediate cooling relief, plus CBD for long-lasting anti-inflammatory benefits.",
    effects: "Localized Pain Relief, Anti-inflammatory, Cooling",
    flavor: "Menthol, Eucalyptus",
    bestFor: "Muscle pain, Joint pain, Post-workout",
    rating: "4.9",
    isFeatured: "yes",
  },
  {
    name: "CBD Muscle Recovery Balm 500mg",
    strain: "Broad Spectrum Hemp Extract",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "1.7",
    price: 3999,
    retailPrice: 5999,
    quantity: 120,
    unit: "2oz tin",
    description: "Designed for athletes and active individuals, our CBD Muscle Recovery Balm combines 500mg of broad spectrum CBD with essential oils of peppermint, lavender, and eucalyptus. Apply after workouts for faster recovery.",
    effects: "Muscle Recovery, Anti-inflammatory, Soothing",
    flavor: "Peppermint, Lavender",
    bestFor: "Post-workout, Athletes, Muscle soreness",
    rating: "4.8",
  },
  {
    name: "CBD Face Serum 250mg Anti-Aging",
    strain: "CBD Isolate",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "0.8",
    price: 4999,
    retailPrice: 7999,
    quantity: 80,
    unit: "1oz bottle",
    description: "Our CBD Anti-Aging Face Serum combines 250mg of CBD isolate with hyaluronic acid, vitamin C, and retinol for a comprehensive anti-aging formula. CBD's antioxidant properties help neutralize free radicals and reduce inflammation.",
    effects: "Anti-aging, Hydrating, Brightening",
    flavor: "Fragrance-free",
    bestFor: "Skincare, Anti-aging, Sensitive skin",
    rating: "4.7",
  },
  {
    name: "CBD Bath Bombs 100mg Each (4-pack)",
    strain: "Full Spectrum Hemp Extract",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "1.0",
    price: 2999,
    retailPrice: 4499,
    quantity: 150,
    unit: "4-pack",
    description: "Transform your bath into a therapeutic experience with our CBD Bath Bombs. Each bomb contains 100mg of full spectrum CBD along with essential oils of lavender, eucalyptus, and peppermint. Skin-softening shea butter included.",
    effects: "Full-body Relaxation, Skin Softening, Stress Relief",
    flavor: "Lavender, Eucalyptus, Peppermint",
    bestFor: "Self-care, Relaxation, Skin health",
    rating: "4.8",
  },
  {
    name: "CBD Lip Balm 25mg (3-pack)",
    strain: "CBD Isolate",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "0.5",
    price: 1499,
    retailPrice: 1999,
    quantity: 200,
    unit: "3-pack",
    description: "Our CBD Lip Balm provides moisturizing relief with 25mg of CBD isolate per stick. Formulated with beeswax, shea butter, and vitamin E for long-lasting hydration. Available in mint, vanilla, and unflavored.",
    effects: "Moisturizing, Healing, Soothing",
    flavor: "Mint, Vanilla, Unflavored",
    bestFor: "Dry lips, Daily use, On-the-go",
    rating: "4.6",
  },

  // ── CBD CAPSULES & SOFTGELS ───────────────────────────────────────────────────
  {
    name: "CBD Softgels 25mg (60-count)",
    strain: "Full Spectrum Hemp Extract",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "2.5",
    price: 5999,
    retailPrice: 8999,
    quantity: 100,
    unit: "60-count bottle",
    description: "Our CBD Softgels offer precise, consistent dosing in an easy-to-swallow format. Each softgel contains 25mg of full spectrum CBD in a base of MCT oil for enhanced bioavailability. No taste, no mess — just clean CBD.",
    effects: "Consistent Relief, Anti-inflammatory, Wellness",
    flavor: "Unflavored",
    bestFor: "Daily supplement, Precise dosing, Travel",
    rating: "4.8",
  },
  {
    name: "CBD + Turmeric Capsules 25mg (30-count)",
    strain: "Full Spectrum Hemp + Turmeric",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "2.5",
    price: 4499,
    retailPrice: 6499,
    quantity: 120,
    unit: "30-count bottle",
    description: "Our CBD + Turmeric Capsules combine 25mg of full spectrum CBD with 500mg of turmeric (95% curcuminoids) and black pepper extract for maximum absorption. A powerful anti-inflammatory combination for joint and muscle health.",
    effects: "Anti-inflammatory, Joint Health, Immune Support",
    flavor: "Unflavored",
    bestFor: "Arthritis, Joint pain, Inflammation",
    rating: "4.9",
    isFeatured: "yes",
  },
  {
    name: "CBD + Ashwagandha Stress Capsules 25mg",
    strain: "Broad Spectrum Hemp + Ashwagandha",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "2.5",
    price: 4999,
    retailPrice: 7499,
    quantity: 100,
    unit: "30-count bottle",
    description: "Our CBD + Ashwagandha Stress Capsules combine 25mg of broad spectrum CBD with 300mg of KSM-66 ashwagandha root extract — clinically proven to reduce cortisol levels. A comprehensive adaptogenic stress formula.",
    effects: "Stress Reduction, Cortisol Balance, Calm Focus",
    flavor: "Unflavored",
    bestFor: "Chronic stress, Anxiety, Adrenal fatigue",
    rating: "4.8",
  },

  // ── CBD VAPES ─────────────────────────────────────────────────────────────────
  {
    name: "CBD Vape Cartridge 1000mg - Sour Diesel",
    strain: "Sour Diesel CBD",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "85.0",
    price: 3999,
    retailPrice: 5999,
    quantity: 150,
    unit: "1ml cartridge",
    description: "Our Sour Diesel CBD Vape Cartridge delivers 1000mg of full spectrum CBD distillate with natural Sour Diesel terpenes. Compatible with standard 510-thread batteries. Fast-acting relief in seconds.",
    effects: "Fast Relief, Energizing, Focus",
    flavor: "Diesel, Citrus, Earthy",
    bestFor: "Fast-acting relief, Daytime use, On-the-go",
    rating: "4.7",
  },
  {
    name: "CBD Vape Cartridge 1000mg - Granddaddy Purple",
    strain: "Granddaddy Purple CBD",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "85.0",
    price: 3999,
    retailPrice: 5999,
    quantity: 130,
    unit: "1ml cartridge",
    description: "Our Granddaddy Purple CBD Vape Cartridge features full spectrum CBD distillate with authentic GDP terpenes — grape, berry, and floral notes. Ideal for evening relaxation and sleep support.",
    effects: "Relaxing, Sedating, Pain Relief",
    flavor: "Grape, Berry, Floral",
    bestFor: "Evening use, Sleep, Pain relief",
    rating: "4.8",
  },
  {
    name: "CBD Disposable Vape Pen 500mg - Pineapple Express",
    strain: "Pineapple Express CBD",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "85.0",
    price: 2499,
    retailPrice: 3499,
    quantity: 200,
    unit: "disposable pen",
    description: "Our Pineapple Express CBD Disposable Vape Pen comes pre-charged and pre-filled with 500mg of full spectrum CBD distillate. No charging, no refilling — just inhale and enjoy the tropical pineapple and mango flavors.",
    effects: "Uplifting, Energizing, Mood Boost",
    flavor: "Pineapple, Mango, Tropical",
    bestFor: "Beginners, Convenience, Travel",
    rating: "4.7",
    isFeatured: "yes",
  },
  {
    name: "CBD Vape Juice 500mg - Blue Raspberry",
    strain: "CBD Isolate",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "5.0",
    price: 2999,
    retailPrice: 4499,
    quantity: 180,
    unit: "30ml bottle",
    description: "Our CBD Vape Juice is compatible with all open-system vape devices. Each 30ml bottle contains 500mg of CBD isolate in a 70/30 VG/PG base. Blue Raspberry flavor with no artificial colors.",
    effects: "Relaxation, Stress Relief, Mild Calm",
    flavor: "Blue Raspberry",
    bestFor: "Existing vapers, Customizable dosing, Flavor variety",
    rating: "4.6",
  },

  // ── CBG PRODUCTS ──────────────────────────────────────────────────────────────
  {
    name: "CBG Flower - White CBG",
    strain: "White CBG",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.1",
    cbdPercentage: "2.0",
    price: 1499,
    retailPrice: 1999,
    quantity: 200,
    unit: "gram",
    description: "White CBG is a rare hemp cultivar bred specifically for high CBG (cannabigerol) content. Known as the 'mother cannabinoid', CBG is the precursor to all other cannabinoids and offers unique therapeutic benefits including neuroprotection and antibacterial properties.",
    effects: "Focus, Neuroprotective, Anti-bacterial",
    flavor: "Pine, Woody, Earthy",
    bestFor: "Focus, Neurological health, Daytime use",
    rating: "4.8",
  },
  {
    name: "CBG + CBD Tincture 1000mg",
    strain: "CBG + CBD Blend",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "2.0",
    price: 6499,
    retailPrice: 9999,
    quantity: 90,
    unit: "30ml bottle",
    description: "Our CBG + CBD Tincture combines equal parts CBG and CBD for a synergistic effect. CBG enhances CBD's therapeutic benefits through the entourage effect. Ideal for those seeking focus, anti-inflammatory, and neuroprotective benefits.",
    effects: "Focus, Anti-inflammatory, Neuroprotective",
    flavor: "Natural Hemp",
    bestFor: "Focus, Inflammation, Neurological health",
    rating: "4.9",
  },

  // ── CBN PRODUCTS ──────────────────────────────────────────────────────────────
  {
    name: "CBN Sleep Oil 500mg",
    strain: "CBN + CBD Blend",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "1.0",
    price: 5499,
    retailPrice: 7999,
    quantity: 80,
    unit: "30ml bottle",
    description: "CBN (cannabinol) is the most sedative of all cannabinoids. Our CBN Sleep Oil combines 500mg of CBN with 500mg of CBD for the most powerful natural sleep aid available. Take 30-60 minutes before bed for deep, restorative sleep.",
    effects: "Deep Sleep, Sedating, Relaxation",
    flavor: "Natural Hemp",
    bestFor: "Severe insomnia, Sleep disorders, Nighttime",
    rating: "4.9",
    isFeatured: "yes",
  },
  {
    name: "CBN Gummies 5mg + CBD 25mg (20-count)",
    strain: "CBN + CBD Blend",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "2.5",
    price: 4999,
    retailPrice: 6999,
    quantity: 100,
    unit: "20-count jar",
    description: "Our CBN + CBD Sleep Gummies combine 5mg of CBN with 25mg of CBD per gummy for a comprehensive sleep formula. Enhanced with L-theanine for additional calming effects. Delicious blackberry flavor.",
    effects: "Sleep, Relaxation, Calm",
    flavor: "Blackberry",
    bestFor: "Insomnia, Sleep quality, Nighttime routine",
    rating: "4.8",
  },

  // ── DELTA-8 THC (HEMP-DERIVED) ────────────────────────────────────────────────
  {
    name: "Delta-8 THC Gummies 25mg (20-count)",
    strain: "Delta-8 Hemp Distillate",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "0.0",
    price: 3499,
    retailPrice: 4999,
    quantity: 150,
    unit: "20-count jar",
    description: "Delta-8 THC is a hemp-derived cannabinoid that produces mild psychoactive effects — often described as a smoother, clearer high than Delta-9 THC. Our 25mg Delta-8 Gummies are federally legal under the 2018 Farm Bill. Check your state laws before purchasing.",
    effects: "Mild Euphoria, Relaxation, Appetite Stimulation",
    flavor: "Watermelon, Mango, Strawberry",
    bestFor: "Mild euphoria, Relaxation, Appetite",
    rating: "4.7",
  },
  {
    name: "Delta-8 THC Vape Cartridge 1000mg",
    strain: "Delta-8 Hemp Distillate",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "0.0",
    price: 3999,
    retailPrice: 5999,
    quantity: 120,
    unit: "1ml cartridge",
    description: "Our Delta-8 THC Vape Cartridge delivers 1000mg of hemp-derived Delta-8 distillate. Federally legal under the 2018 Farm Bill. Produces a clear-headed, mild euphoric effect without the anxiety associated with Delta-9 THC.",
    effects: "Mild Euphoria, Clear-headed, Relaxing",
    flavor: "Natural Terpenes",
    bestFor: "Mild euphoria, Anxiety-free high, Relaxation",
    rating: "4.6",
  },

  // ── HEMP CONCENTRATES ─────────────────────────────────────────────────────────
  {
    name: "CBD Wax Concentrate 1g - Sour Space Candy",
    strain: "Sour Space Candy",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "70.0",
    price: 2999,
    retailPrice: 4499,
    quantity: 100,
    unit: "gram",
    description: "Our CBD Wax Concentrate is a high-potency hemp extract containing 70% CBD. Made using BHO extraction and purged to remove all solvents. Ideal for dabbing or adding to flower for an enhanced experience.",
    effects: "Potent Relief, Fast-acting, Anti-inflammatory",
    flavor: "Sour Apple, Tropical",
    bestFor: "Experienced users, Dabbing, High-potency needs",
    rating: "4.7",
  },
  {
    name: "CBD Live Resin 1g - Cherry Wine",
    strain: "Cherry Wine",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "65.0",
    price: 3999,
    retailPrice: 5999,
    quantity: 80,
    unit: "gram",
    description: "Our CBD Live Resin is extracted from fresh-frozen hemp flower to preserve the full terpene profile. The result is a concentrate that captures the authentic aroma and flavor of Cherry Wine with an exceptionally rich cannabinoid profile.",
    effects: "Full-spectrum Relief, Aromatic, Potent",
    flavor: "Cherry, Black Pepper, Floral",
    bestFor: "Connoisseurs, Dabbing, Maximum terpenes",
    rating: "4.9",
    isFeatured: "yes",
  },
  {
    name: "CBD Shatter 1g - Elektra",
    strain: "Elektra",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "75.0",
    price: 2499,
    retailPrice: 3999,
    quantity: 100,
    unit: "gram",
    description: "CBD Shatter is a glass-like concentrate with 75% CBD content. Made from Elektra hemp flower using butane extraction and vacuum purging. Breaks into shards for easy dosing. Best for dabbing or vaporizing.",
    effects: "Fast-acting, Potent, Clean",
    flavor: "Orange, Citrus, Pine",
    bestFor: "Dabbing, Experienced users, Fast relief",
    rating: "4.7",
  },

  // ── HEMP WELLNESS BUNDLES ─────────────────────────────────────────────────────
  {
    name: "Complete CBD Wellness Bundle",
    strain: "Mixed Full Spectrum",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "3.0",
    price: 14999,
    retailPrice: 24999,
    quantity: 50,
    unit: "bundle",
    description: "Our Complete CBD Wellness Bundle includes everything you need to start your CBD journey: 1000mg CBD Oil, 25mg CBD Gummies (30-count), CBD Pain Relief Cream (500mg), and Sour Space Candy Hemp Flower (3.5g). Save over 40% vs. buying individually.",
    effects: "Comprehensive Wellness, Full-body Relief",
    flavor: "Mixed",
    bestFor: "Beginners, Gift sets, Maximum value",
    rating: "4.9",
    isFeatured: "yes",
  },
  {
    name: "CBD Sleep Bundle",
    strain: "Mixed CBD + CBN",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.3",
    cbdPercentage: "2.5",
    price: 11999,
    retailPrice: 18999,
    quantity: 60,
    unit: "bundle",
    description: "Our CBD Sleep Bundle is designed to help you achieve deep, restorative sleep naturally. Includes: CBD Sleep Tincture 750mg, CBN Sleep Gummies (20-count), Cherry Wine Hemp Flower (3.5g), and CBD Bath Bomb (100mg). The complete nighttime routine.",
    effects: "Deep Sleep, Relaxation, Stress Relief",
    flavor: "Mixed",
    bestFor: "Insomnia, Sleep quality, Nighttime routine",
    rating: "4.9",
    isFeatured: "yes",
  },
  {
    name: "CBD Sports Recovery Bundle",
    strain: "Mixed Broad Spectrum",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "2.5",
    price: 12999,
    retailPrice: 19999,
    quantity: 50,
    unit: "bundle",
    description: "Designed for athletes and fitness enthusiasts. Includes: CBD Muscle Recovery Balm 500mg, CBD + Turmeric Capsules (30-count), CBD Energy Gummies (30-count), and Broad Spectrum CBD Oil 1500mg. Everything you need for peak performance and recovery.",
    effects: "Recovery, Anti-inflammatory, Energy",
    flavor: "Mixed",
    bestFor: "Athletes, Post-workout, Active lifestyle",
    rating: "4.8",
  },
  {
    name: "CBD Starter Kit",
    strain: "Broad Spectrum Hemp Extract",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "2.5",
    price: 5999,
    retailPrice: 9999,
    quantity: 100,
    unit: "kit",
    description: "New to CBD? Our CBD Starter Kit includes everything a beginner needs: CBD Isolate Oil 500mg, CBD Gummies 25mg (10-count), and a comprehensive CBD Guide. Start your wellness journey with confidence.",
    effects: "Gentle Introduction, Relaxation, Wellness",
    flavor: "Mixed",
    bestFor: "Beginners, First-time users, Gifting",
    rating: "4.8",
  },

  // ── HEMP SEEDS & CULTIVATION ──────────────────────────────────────────────────
  {
    name: "High-CBD Hemp Seeds - Sour Space Candy (10-pack)",
    strain: "Sour Space Candy",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.2",
    cbdPercentage: "18.0",
    price: 4999,
    retailPrice: 7999,
    quantity: 100,
    unit: "10-seed pack",
    description: "Certified high-CBD hemp seeds for licensed farmers. Sour Space Candy genetics produce plants with 18-22% CBD and <0.3% THC. Feminized seeds with 99% germination rate. Certificate of Analysis included.",
    effects: "N/A - Cultivation Product",
    flavor: "N/A",
    bestFor: "Licensed hemp farmers, Cultivation, B2B",
    rating: "4.8",
  },
  {
    name: "High-CBD Hemp Seeds - Cherry Wine (10-pack)",
    strain: "Cherry Wine",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.15",
    cbdPercentage: "16.0",
    price: 4499,
    retailPrice: 6999,
    quantity: 100,
    unit: "10-seed pack",
    description: "Certified Cherry Wine hemp seeds for licensed farmers. Feminized, photoperiod genetics producing dense, resinous buds with 14-18% CBD. Excellent mold resistance. Ideal for both indoor and outdoor cultivation.",
    effects: "N/A - Cultivation Product",
    flavor: "N/A",
    bestFor: "Licensed hemp farmers, Cultivation, B2B",
    rating: "4.7",
  },

  // ── HEMP PROTEIN & NUTRITION ──────────────────────────────────────────────────
  {
    name: "Organic Hemp Protein Powder 2lb",
    strain: "Industrial Hemp",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "0.0",
    price: 2999,
    retailPrice: 3999,
    quantity: 200,
    unit: "2lb bag",
    description: "Our Organic Hemp Protein Powder is made from cold-pressed hemp seeds and contains 15g of complete protein per serving with all 9 essential amino acids. Rich in omega-3 and omega-6 fatty acids. USDA Organic certified, non-GMO, and vegan.",
    effects: "Muscle Building, Nutrition, Energy",
    flavor: "Natural, Chocolate available",
    bestFor: "Athletes, Vegans, Protein supplementation",
    rating: "4.7",
  },
  {
    name: "Hemp Hearts (Shelled Hemp Seeds) 1lb",
    strain: "Industrial Hemp",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "0.0",
    price: 1499,
    retailPrice: 1999,
    quantity: 300,
    unit: "1lb bag",
    description: "Organic shelled hemp seeds (hemp hearts) are a nutritional powerhouse. Three tablespoons provide 10g of complete protein, 15g of healthy fats, and 1g of fiber. Add to smoothies, salads, yogurt, or oatmeal.",
    effects: "Nutrition, Heart Health, Omega Fatty Acids",
    flavor: "Mild Nutty",
    bestFor: "Daily nutrition, Cooking, Smoothies",
    rating: "4.8",
  },
  {
    name: "Cold-Pressed Hemp Seed Oil 16oz",
    strain: "Industrial Hemp",
    category: "hemp",
    isHemp: "yes",
    thcPercentage: "0.0",
    cbdPercentage: "0.0",
    price: 1999,
    retailPrice: 2999,
    quantity: 200,
    unit: "16oz bottle",
    description: "Our cold-pressed hemp seed oil has the ideal 3:1 ratio of omega-6 to omega-3 fatty acids. Rich in gamma-linolenic acid (GLA) for heart and skin health. Use as a salad dressing, in smoothies, or as a skin moisturizer.",
    effects: "Heart Health, Skin Health, Omega Balance",
    flavor: "Light Nutty",
    bestFor: "Cooking, Skincare, Nutrition",
    rating: "4.7",
  },
];

async function seedHempProducts() {
  const conn = await mysql.createConnection(process.env.DATABASE_URL);
  
  console.log(`Seeding ${hempProducts.length} hemp/CBD products...`);
  
  let inserted = 0;
  let skipped = 0;
  
  for (const product of hempProducts) {
    try {
      // Check if product already exists by name
      const [existing] = await conn.execute(
        'SELECT id FROM products WHERE name = ? LIMIT 1',
        [product.name]
      );
      
      if (existing.length > 0) {
        console.log(`  SKIP: ${product.name} (already exists)`);
        skipped++;
        continue;
      }
      
      await conn.execute(
        `INSERT INTO products 
          (farmerId, name, strain, category, isHemp, thcPercentage, cbdPercentage, 
           price, retailPrice, quantity, unit, description, effects, flavor, bestFor, 
           rating, status, isFeatured, isSponsored, isPreOrder, views, clicks)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', ?, 'no', 'no', 0, 0)`,
        [
          FARMER_ID,
          product.name,
          product.strain,
          product.category,
          product.isHemp,
          product.thcPercentage || null,
          product.cbdPercentage || null,
          product.price,
          product.retailPrice || null,
          product.quantity,
          product.unit,
          product.description || null,
          product.effects || null,
          product.flavor || null,
          product.bestFor || null,
          product.rating || '4.5',
          product.isFeatured === 'yes' ? 'yes' : 'no',
        ]
      );
      
      console.log(`  OK: ${product.name} ($${(product.price/100).toFixed(2)}/${product.unit})`);
      inserted++;
    } catch (err) {
      console.error(`  ERROR: ${product.name}: ${err.message}`);
    }
  }
  
  await conn.end();
  
  console.log(`\nDone! Inserted: ${inserted}, Skipped: ${skipped}`);
  
  // Final count
  const conn2 = await mysql.createConnection(process.env.DATABASE_URL);
  const [total] = await conn2.execute("SELECT COUNT(*) as count FROM products WHERE isHemp='yes'");
  console.log(`Total hemp products in DB: ${total[0].count}`);
  await conn2.end();
}

seedHempProducts().catch(console.error);
